### ISSUE TITLE
State History Not Loading In More Panel For Entities

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#1796]
**Home Assistant release with the issue:**

0.80.2
**Last working Home Assistant release (if known):**

0.79.3
**Browser and Operating System:**

Windows 10 Chrome v70 (happens in incognito as well)
**Description of problem:**

When we select any entity to bring up the more info panel the state history stays on "loading state history..." This happens for any entity.

![image](https://user-images.githubusercontent.com/1634145/47105823-daa35800-d1f9-11e8-964b-b42880cbea72.png)

**Javascript errors shown in the web inspector (if applicable):**
```
none
```

**Additional information:**
This happens in dev and also in lovelace and standard UI.

**Comment by cgarwood** [comment]
Seeing the same on latest frontend builds. This is all that is going through the websocket when selecting an entity:
```
connection-mixin.js:116 Sending {type: "config/entity_registry/get", entity_id: "binary_sensor.front_door_sensor"}
connection-mixin.js:121 Received {entity_id: "binary_sensor.front_door_sensor", name: null}
```

**Comment by VDRainer** [comment]
Same issue in LL card `- type: history-graph`

**Comment by danbowkley** [comment]
Yup, me too. Worked fine on 0.80.1, upgraded this morning and all history graphs are dead across the board. Stuck on "Loading state history..."

**Comment by christopheBfr** [comment]
The same behaviour on my side.

Please provide a patch for this problem quickly 🙏

Thank you for your perfect jobs on ha!

**Comment by lbschenkel** [comment]
Same here, on 0.80.2. I'm also seeing the following on the server logs:
```
ERROR (MainThread) [frontend.js.latest.201810170] https://redacted/frontend_latest/ee75d8d43fc454407590.chunk.js:1747:2036 TypeError: sortable[2] is undefined
ERROR (MainThread) [frontend.js.latest.201810170] https://redacted/frontend_latest/app-96e769d2.js:4834:2416 TypeError: localize is not a function
ERROR (MainThread) [frontend.js.latest.201810170] https://redacted/frontend_latest/ee75d8d43fc454407590.chunk.js:1747:1971 Uncaught TypeError: Cannot read property '1' of undefined
```

**Comment by deviant-studio** [comment]
I guess my issue is related so i post it here:
After upgrading to 0.80.0(0.80.1, 0.80.2) Firefox stopped to update the Lovelace UI (switches, sensors, graphs are frozen and not respond on state changes)
In the Chrome i got broken graphs as stated other folks.

**Comment by balloob** [comment]
fixed in 80.3

**Comment by imist** [comment]
Same for me, upgraded to 0.80.3 but still no history loading.

**Comment by imist** [comment]
> Same for me, upgraded to 0.80.3 but still no history loading.

I take that back. Now all of a sudden it's working :-)

**Comment by d0ugal** [comment]
Possibly browser cache or something? Make sure you reload etc. I had weirdness when I upgraded from a broken version but then it was all good.

**Comment by JPM-git** [comment]
So, I can get some graphics to load on "start", but none is ever updated ad none can show "details" after click on it.

Also the graphs that show up after a restart aren't always the same.

I've clear the cache-> Didn't work
Try a new browser -> Didn't work

Downgrade to 0.81 (last backup i had) and everything worked as usual so.

**Comment by balloob** [comment]
Please do not continue discussion on closed issues. Try out 81 that will be released today, if you can still repro, please open a new issue.
