### ISSUE TITLE
Regression: Changing the set temperature of a climate component via the web UI no longer works.

### ISSUE THREAD

**Issue by nkaminski** [home-assistant/home-assistant-polymer#567]
Hello,
After updating to release 0.57.1 from 0.56.2, I am no longer able to change the temperature setpoint of any climate control devices via the web UI. This looks to be a regression resulting from PR #538, and I plan to look into this myself since it looks like the fix may be quite trivial.

When the unexpected behavior occurs, the following error is logged in the browser Javascript console:
    Uncaught TypeError: e.fire is not a function

**Comment by balloob** [comment]
Ah yes, we're missing the event mixin.

CC @armills
